language: objective-c
osx_image: xcode10.1
xcode_workspace: CISample.xcworkspace
xcode_scheme: CISample
xcode_sdk: iphonesimulator

before_install:
- pod install
- brew update
- brew install carthage
- carthage bootstrap --platform ios

branches:
  only:
    - travisci
