language: swift
osx_image: xcode10.1

before_install:
- pod install
- brew update
- brew install carthage
- carthage update --platform ios

cache:
  directories:
  - Pods
  - Carthage

branches:
  only:
    - master
