language: objective-c
osx_image: xcode10.1

before_install:
- pod install
- brew update
- brew install carthage
- carthage bootstrap --platform ios

branches:
  only:
    - fastlane

script:
  - fastlane adhoc
 