default_platform :ios

platform :ios do
  before_all do
    setup_travis
  end

  desc "Runs all the tests"
  lane :test do
    scan
    snapshot
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(git_url: "https://github.com/opst/ioscertificates",
          type: "enterprise",
          app_identifier: "jp.co.opst.CISample",
          username: "ios-developers-admin@opst.co.jp")
    gym(export_method: "enterprise")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")
    gym(export_method: "app-store")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end
end
